### ISSUE TITLE
Version 2.2.0 - Unity 2022.3.24f1 - NullReferenceException

### ISSUE THREAD

**Issue by huran438** [SolarianZ/UnityAssetQuickAccessTool#5]
NullReferenceException when exiting PlayMode

![image](https://github.com/SolarianZ/UnityAssetQuickAccessTool/assets/1672637/ae20880a-1d94-4a59-b939-8e6dc1ba39b8)

**Comment by SolarianZ** [comment]
Hi @huran438 ,

Thank you for your feedback. Please close the Asset Quick Access window or bring it to the foreground temporarily to resolve the issue. I will submit a fix later.
